// ============================================================================
// tb_tlmm_engine.sv — Testbench for TLMM Engine
//
// Tests the tlmm_top module with known test vectors.
// Loads activation LUT and weight indices, runs computation,
// checks result against expected value, and reports cycle count.
//
// This testbench is parameterized via `define so you can run:
//   G=3 (TeLLMe baseline)
//   G=4 (our design)
//
// Test vectors are generated by the Python script gen_test_vectors.py
// and loaded via $readmemh.
//
// Author: Rajat Gupta
// ============================================================================

`timescale 1ns / 1ps

// Default to G=4 if not defined externally
`ifndef TEST_G
`define TEST_G 4
`endif

`ifndef TEST_K
`define TEST_K 2560
`endif

module tb_tlmm_engine;

    // ---------------------------------------------------------------
    // Parameters
    // ---------------------------------------------------------------
    localparam int G           = `TEST_G;
    localparam int K           = `TEST_K;
    localparam int VALUE_WIDTH = 16;
    localparam int ACC_WIDTH   = 32;
    localparam int NUM_GROUPS  = (K + G - 1) / G;
    localparam int NUM_LUT_ENTRIES = 3 ** G;
    localparam int LUT_ADDR_W = $clog2(NUM_LUT_ENTRIES);
    localparam int GRP_ADDR_W = $clog2(NUM_GROUPS);

    // ---------------------------------------------------------------
    // Clock and reset
    // ---------------------------------------------------------------
    logic clk = 0;
    logic rst_n = 0;
    always #2.5 clk = ~clk;  // 200 MHz

    // ---------------------------------------------------------------
    // DUT signals
    // ---------------------------------------------------------------
    logic                    act_lut_wen;
    logic [LUT_ADDR_W-1:0]  act_lut_waddr;
    logic [VALUE_WIDTH-1:0]  act_lut_wdata;
    logic                    widx_wen;
    logic [GRP_ADDR_W-1:0]  widx_waddr;
    logic [LUT_ADDR_W-1:0]  widx_wdata;
    logic                    start;
    logic                    done;
    logic                    busy;
    logic [ACC_WIDTH-1:0]    result;
    logic                    result_valid;

    // ---------------------------------------------------------------
    // DUT instantiation
    // ---------------------------------------------------------------
    tlmm_top #(
        .G          (G),
        .K          (K),
        .VALUE_WIDTH(VALUE_WIDTH),
        .ACC_WIDTH  (ACC_WIDTH)
    ) dut (
        .clk            (clk),
        .rst_n          (rst_n),
        .act_lut_wen    (act_lut_wen),
        .act_lut_waddr  (act_lut_waddr),
        .act_lut_wdata  (act_lut_wdata),
        .widx_wen       (widx_wen),
        .widx_waddr     (widx_waddr),
        .widx_wdata     (widx_wdata),
        .start          (start),
        .done           (done),
        .busy           (busy),
        .result         (result),
        .result_valid   (result_valid)
    );

    // ---------------------------------------------------------------
    // Test vector storage
    // ---------------------------------------------------------------
    logic [VALUE_WIDTH-1:0] tv_act_lut [0:NUM_LUT_ENTRIES-1];
    logic [LUT_ADDR_W-1:0]  tv_widx    [0:NUM_GROUPS-1];
    logic [ACC_WIDTH-1:0]    tv_expected;

    // ---------------------------------------------------------------
    // Test tasks
    // ---------------------------------------------------------------
    int cycle_count;
    int num_tests_passed;
    int num_tests_failed;

    task automatic load_activation_lut();
        for (int i = 0; i < NUM_LUT_ENTRIES; i++) begin
            @(posedge clk);
            act_lut_wen   <= 1'b1;
            act_lut_waddr <= i[LUT_ADDR_W-1:0];
            act_lut_wdata <= tv_act_lut[i];
        end
        @(posedge clk);
        act_lut_wen <= 1'b0;
    endtask

    task automatic load_weight_indices();
        for (int i = 0; i < NUM_GROUPS; i++) begin
            @(posedge clk);
            widx_wen   <= 1'b1;
            widx_waddr <= i[GRP_ADDR_W-1:0];
            widx_wdata <= tv_widx[i];
        end
        @(posedge clk);
        widx_wen <= 1'b0;
    endtask

    task automatic run_and_check(input int test_num, input logic signed [ACC_WIDTH-1:0] expected);
        // Start computation
        @(posedge clk);
        start <= 1'b1;
        cycle_count = 0;
        @(posedge clk);
        start <= 1'b0;

        // Wait for done
        while (!done) begin
            @(posedge clk);
            cycle_count++;
        end

        // Check result
        if ($signed(result) == $signed(expected)) begin
            $display("TEST %0d PASSED: G=%0d K=%0d result=%0d expected=%0d cycles=%0d",
                     test_num, G, K, $signed(result), $signed(expected), cycle_count);
            num_tests_passed++;
        end else begin
            $display("TEST %0d FAILED: G=%0d K=%0d result=%0d expected=%0d cycles=%0d",
                     test_num, G, K, $signed(result), $signed(expected), cycle_count);
            num_tests_failed++;
        end
    endtask

    // ---------------------------------------------------------------
    // Deterministic test vector generation (no file I/O needed)
    // Uses LFSR-like pattern for reproducibility
    // ---------------------------------------------------------------
    task automatic generate_test_vectors(input int seed);
        automatic int lfsr = seed;
        automatic int signed acc = 0;
        automatic int signed act_vals [0:G-1];
        
        // Generate random activation values (INT8 range: -128 to 127)
        // Build LUT: for each possible ternary combination, compute dot product
        for (int entry = 0; entry < NUM_LUT_ENTRIES; entry++) begin
            automatic int signed partial = 0;
            automatic int temp = entry;
            for (int j = 0; j < G; j++) begin
                automatic int trit = temp % 3;  // 0, 1, 2
                automatic int signed w = trit - 1;  // -1, 0, +1
                temp = temp / 3;
                
                // Deterministic activation from LFSR
                if (entry == 0) begin
                    lfsr = lfsr * 1103515245 + 12345;
                    act_vals[j] = ((lfsr >> 16) & 8'hFF);
                    if (act_vals[j] > 127) act_vals[j] = act_vals[j] - 256;
                end
                
                partial = partial + w * act_vals[j];
            end
            tv_act_lut[entry] = partial[VALUE_WIDTH-1:0];
        end
        
        // Generate weight indices and compute expected result
        acc = 0;
        for (int g = 0; g < NUM_GROUPS; g++) begin
            lfsr = lfsr * 1103515245 + 12345;
            automatic int idx = ((lfsr >> 16) & 32'h7FFFFFFF) % NUM_LUT_ENTRIES;
            tv_widx[g] = idx[LUT_ADDR_W-1:0];
            acc = acc + $signed({{(ACC_WIDTH-VALUE_WIDTH){tv_act_lut[idx][VALUE_WIDTH-1]}}, 
                                  tv_act_lut[idx]});
        end
        tv_expected = acc[ACC_WIDTH-1:0];
    endtask

    // ---------------------------------------------------------------
    // Main test sequence
    // ---------------------------------------------------------------
    initial begin
        // Initialize
        act_lut_wen   = 0;
        act_lut_waddr = 0;
        act_lut_wdata = 0;
        widx_wen      = 0;
        widx_waddr    = 0;
        widx_wdata    = 0;
        start         = 0;
        num_tests_passed = 0;
        num_tests_failed = 0;

        // Reset
        rst_n = 0;
        repeat (10) @(posedge clk);
        rst_n = 1;
        repeat (5) @(posedge clk);

        $display("============================================================");
        $display("TLMM Engine Testbench: G=%0d, K=%0d, NUM_GROUPS=%0d", G, K, NUM_GROUPS);
        $display("LUT entries: %0d, Index width: %0d bits", NUM_LUT_ENTRIES, LUT_ADDR_W);
        $display("============================================================");

        // Run multiple tests with different seeds
        for (int t = 0; t < 5; t++) begin
            $display("\n--- Test %0d ---", t);
            generate_test_vectors(42 + t * 1000);
            load_activation_lut();
            load_weight_indices();
            repeat (2) @(posedge clk);  // Small gap
            run_and_check(t, tv_expected);
        end

        // Summary
        $display("\n============================================================");
        $display("SUMMARY: G=%0d K=%0d", G, K);
        $display("  Passed: %0d", num_tests_passed);
        $display("  Failed: %0d", num_tests_failed);
        $display("  Groups per dot product: %0d", NUM_GROUPS);
        $display("  Cycles per dot product: ~%0d (last test)", cycle_count);
        $display("============================================================");

        if (num_tests_failed > 0)
            $display("*** SOME TESTS FAILED ***");
        else
            $display("*** ALL TESTS PASSED ***");

        $finish;
    end

    // Timeout
    initial begin
        #(1_000_000 * NUM_GROUPS);  // Scale timeout with problem size
        $display("TIMEOUT!");
        $finish;
    end

endmodule
