"""Step 4: Export LUT indices as FPGA BRAM initialization files.

Generates:
    - .coe files: Xilinx Coefficient files for Block RAM IP
    - .mem files: Vivado memory initialization files (hex)
    - .sv header: SystemVerilog constants and parameters

The FPGA reads these LUT index arrays from BRAM at runtime. For each
group of 4 ternary weights, the stored index (0..80) tells the hardware
which precomputed partial sum to use.

BRAM layout per tile:
    - Each tile has shape (block_rows, block_cols // group_size) of uint8 indices
    - Packed into BRAM words of configurable width (default 18 bits for BRAM18)
    - Multiple indices can be packed per BRAM word since each index needs only 7 bits
      (ceil(log2(81)) = 7 bits per index)

For Xilinx UltraScale+:
    - BRAM18: 1024 × 18 bits = 18 Kb
    - BRAM36: 1024 × 36 bits = 36 Kb (or 512 × 72 bits)
    - Can pack 2 indices per BRAM18 word (2 × 7 = 14 bits, fits in 18)
"""

import logging
import math
from pathlib import Path

import numpy as np
try:
    from tqdm import tqdm
except ImportError:
    def tqdm(iterable, **kwargs):
        return iterable

from .utils import ensure_dir, load_json, save_json

logger = logging.getLogger("bitnet2lut")

# Bits needed per LUT index: ceil(log2(81)) = 7 for group_size=4
BITS_PER_INDEX_G4 = 7


def indices_to_coe(
    indices: np.ndarray,
    output_path: str | Path,
    radix: int = 16,
    bit_width: int = 8,
) -> None:
    """Export LUT indices as Xilinx .coe (Coefficient) file.

    Format:
        memory_initialization_radix=16;
        memory_initialization_vector=
        1A, 2B, 3C, ...;

    Args:
        indices: Flattened array of uint8 LUT indices
        output_path: Path to write .coe file
        radix: Number base (2, 10, or 16)
        bit_width: Bits per entry (for hex formatting)
    """
    flat = indices.flatten().astype(np.uint8)
    hex_chars = bit_width // 4  # digits per value

    with open(output_path, "w") as f:
        f.write(f"memory_initialization_radix={radix};\n")
        f.write("memory_initialization_vector=\n")

        for i, val in enumerate(flat):
            if radix == 16:
                entry = f"{val:0{hex_chars}X}"
            elif radix == 2:
                entry = f"{val:0{bit_width}b}"
            else:
                entry = str(val)

            if i < len(flat) - 1:
                f.write(f"{entry},\n")
            else:
                f.write(f"{entry};\n")


def indices_to_mem(
    indices: np.ndarray,
    output_path: str | Path,
    bit_width: int = 8,
) -> None:
    """Export LUT indices as Vivado .mem file.

    Format: One hex value per line, with optional @address prefix.
        @0000 1A
        @0001 2B
        ...

    Args:
        indices: Flattened array of uint8 LUT indices
        output_path: Path to write .mem file
        bit_width: Bits per entry
    """
    flat = indices.flatten().astype(np.uint8)
    hex_chars = bit_width // 4
    addr_chars = max(4, len(f"{len(flat) - 1:X}"))

    with open(output_path, "w") as f:
        for i, val in enumerate(flat):
            f.write(f"@{i:0{addr_chars}X} {val:0{hex_chars}X}\n")


def generate_sv_header(
    tiling_summary: dict,
    lut_summary: dict,
    output_path: str | Path,
) -> None:
    """Generate SystemVerilog header with architecture constants.

    This header provides all the parameters the RTL needs to instantiate
    the LUT-based inference engine.
    """
    group_size = lut_summary["group_size"]
    num_configs = lut_summary["num_configs"]
    bits_per_index = math.ceil(math.log2(num_configs))
    block_rows = tiling_summary["block_rows"]
    block_cols = tiling_summary["block_cols"]
    groups_per_row = block_cols // group_size

    with open(output_path, "w") as f:
        f.write("// Auto-generated by bitnet2lut — DO NOT EDIT\n")
        f.write("// BitNet b1.58 2B4T LUT inference parameters\n")
        f.write(f"// Generated for block_size=({block_rows}, {block_cols}), ")
        f.write(f"group_size={group_size}\n\n")
        f.write("`ifndef BITNET_LUT_PARAMS_SVH\n")
        f.write("`define BITNET_LUT_PARAMS_SVH\n\n")

        f.write("// === Model architecture ===\n")
        f.write("parameter HIDDEN_SIZE       = 2560;\n")
        f.write("parameter INTERMEDIATE_SIZE = 6912;\n")
        f.write("parameter NUM_LAYERS        = 30;\n")
        f.write("parameter NUM_ATTN_HEADS    = 20;\n")
        f.write("parameter NUM_KV_HEADS      = 5;\n")
        f.write("parameter HEAD_DIM          = 128;\n")
        f.write("parameter VOCAB_SIZE        = 128256;\n")
        f.write("parameter MAX_SEQ_LEN       = 4096;\n\n")

        f.write("// === LUT configuration ===\n")
        f.write(f"parameter LUT_GROUP_SIZE    = {group_size};\n")
        f.write(f"parameter LUT_NUM_CONFIGS   = {num_configs};\n")
        f.write(f"parameter LUT_INDEX_BITS    = {bits_per_index};\n\n")

        f.write("// === Tile configuration ===\n")
        f.write(f"parameter TILE_ROWS         = {block_rows};\n")
        f.write(f"parameter TILE_COLS         = {block_cols};\n")
        f.write(f"parameter GROUPS_PER_ROW    = {groups_per_row};\n")
        f.write(f"parameter INDICES_PER_TILE  = {block_rows * groups_per_row};\n\n")

        f.write("// === BRAM sizing ===\n")
        f.write("// Each index needs LUT_INDEX_BITS bits.\n")
        f.write(f"// Indices per tile: {block_rows} × {groups_per_row} = ")
        f.write(f"{block_rows * groups_per_row}\n")
        indices_per_bram18 = 1024 * 18 // bits_per_index
        f.write(f"// BRAM18 capacity: {indices_per_bram18} indices ")
        f.write(f"(at {bits_per_index} bits each)\n")
        brams_per_tile = math.ceil(
            (block_rows * groups_per_row * bits_per_index) / (1024 * 18)
        )
        f.write(f"// BRAM18s per tile: {brams_per_tile}\n\n")

        f.write("// === Activation quantization ===\n")
        f.write("parameter ACT_BITS          = 8;   // INT8 activations\n")
        f.write("parameter ACT_QUANT_METHOD  = 0;   // 0=absmax per-token\n\n")

        f.write("// === LUT runtime parameters ===\n")
        f.write("// At runtime, for each group position, the FPGA builds a\n")
        f.write(f"// {num_configs}-entry LUT from the current {group_size} ")
        f.write("activation values.\n")
        f.write(f"// Each LUT entry is a partial sum of up to {group_size} ")
        f.write("INT8 activations.\n")
        max_partial = group_size * 127  # max possible partial sum with INT8
        bits_partial = math.ceil(math.log2(2 * max_partial + 1))
        f.write(f"// Max partial sum magnitude: ±{max_partial}\n")
        f.write(f"parameter LUT_ENTRY_BITS    = {bits_partial};\n\n")

        f.write("`endif // BITNET_LUT_PARAMS_SVH\n")

    logger.info(f"SystemVerilog header written to {output_path}")


def export_fpga(
    lut_dir: str | Path,
    tiling_map_path: str | Path,
    lut_summary_path: str | Path,
    output_dir: str | Path,
    formats: list[str] | None = None,
    hw_bit_width: int = 8,
) -> dict:
    """Export all LUT indices as FPGA initialization files.

    Args:
        lut_dir: Directory containing lut_indices/ from Step 3
        tiling_map_path: Path to tiling_map.json from Step 2
        lut_summary_path: Path to lut_summary.json from Step 3
        output_dir: Where to write FPGA files
        formats: List of formats to export ("coe", "mem", "sv")
        hw_bit_width: Bit width per index in hardware files

    Returns:
        Summary dictionary
    """
    lut_dir = Path(lut_dir)
    output_dir = ensure_dir(output_dir)

    if formats is None:
        formats = ["coe", "mem", "sv"]

    tiling_summary = load_json(tiling_map_path) if Path(tiling_map_path).exists() else {}
    lut_summary = load_json(lut_summary_path)

    # Load tiling summary for SV header
    tiling_summ_path = Path(tiling_map_path).parent / "tiling_summary.json"
    tiling_summ = load_json(tiling_summ_path) if tiling_summ_path.exists() else {
        "block_rows": 128, "block_cols": 128
    }

    # Generate SV header
    if "sv" in formats:
        sv_path = output_dir / "bitnet_lut_params.svh"
        generate_sv_header(tiling_summ, lut_summary, sv_path)

    # Export .coe and .mem files for each tile
    lut_indices_dir = lut_dir / "lut_indices"
    if not lut_indices_dir.exists():
        lut_indices_dir = lut_dir  # fallback

    total_files = 0

    for layer_dir in tqdm(
        sorted(lut_indices_dir.iterdir()), desc="Exporting FPGA files"
    ):
        if not layer_dir.is_dir():
            continue

        for proj_dir in sorted(layer_dir.iterdir()):
            if not proj_dir.is_dir():
                continue

            for tile_path in sorted(proj_dir.glob("tile_*.npy")):
                indices = np.load(tile_path)
                stem = tile_path.stem
                rel_dir = f"{layer_dir.name}/{proj_dir.name}"

                if "coe" in formats:
                    coe_dir = ensure_dir(output_dir / "coe" / rel_dir)
                    indices_to_coe(
                        indices, coe_dir / f"{stem}.coe",
                        bit_width=hw_bit_width,
                    )
                    total_files += 1

                if "mem" in formats:
                    mem_dir = ensure_dir(output_dir / "mem" / rel_dir)
                    indices_to_mem(
                        indices, mem_dir / f"{stem}.mem",
                        bit_width=hw_bit_width,
                    )
                    total_files += 1

    summary = {
        "formats_exported": formats,
        "hw_bit_width": hw_bit_width,
        "total_files_written": total_files,
    }

    save_json(summary, output_dir / "export_summary.json")
    logger.info(f"Exported {total_files} FPGA files to {output_dir}")

    return summary
